baseURL = 'http://getthebookofyou.com/'
languageCode = 'en-us'
languageName = "English"
title = 'Get The Book of You'

theme="LoveIt"

[params]
[params.header]
[params.header.title]
name="The Book of You"
logo="/logo.png"
[author]
name = "Shaun Hubbard"
email = "shaun@shauncodes.com"
link = "https://shauncodes.com"
[params.home.profile]
enable = true
# Gravatar Email for preferred avatar in home page
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = ""
# URL of avatar shown in home page
# 主页显示头像的 URL
avatarURL = ""
# title shown in home page (HTML format is supported)
# 主页显示的网站标题 (支持 HTML 格式)
title = "Welcome to the Book of You"
# subtitle shown in home page (HTML format is supported)
# 主页显示的网站副标题 (允许 HTML 格式)
subtitle = "This app is for your journey towards the \"version of you\" you want."
# whether to use typeit animation for subtitle
# 是否为副标题显示打字机动画
typeit = false
# whether to show social links
# 是否显示社交账号
social = true
# disclaimer (HTML format is supported)
# 免责声明 (支持 HTML 格式)
disclaimer = ""
marketingImages= [
    { url = "ios_cover.jpeg", alt = "Cover for iOS app" },
    { url = "ios_index_example.jpeg", alt = "Index for iOS app" },
]


# Menu config
[menu]
[[menu.main]]
weight = 1
identifier = "release-notes"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
name = "Release Notes"
url = "/release-notes/"
# title will be shown when you hover on this menu link
title = "Release Notes"
[[menu.main]]
weight = 2
identifier = "privacy-policy"
# you can add extra information before the name (HTML format is supported), such as icons
pre = ""
# you can add extra information after the name (HTML format is supported), such as icons
post = ""
name = "Privacy Policy"
url = "/privacy-policy/"
# title will be shown when you hover on this menu link
title = "Privacy Policy"

# Markup related configuration in Hugo
[markup]
# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
